name: Asset Release Workflow

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository code
      - name: 👉 Checkout code
        uses: actions/checkout@v3

      # 2. Install necessary packages: zip and rsync
      - name: 🗄 Install zip and rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y zip rsync

      # 3. Create the required directory structure
      - name: 📂 Create required directory structure
        run: |
          mkdir customs-fees-for-woocommerce
          rsync -av \
            --exclude="customs-fees-for-woocommerce" \
            --exclude="assets" \
            --exclude="src" \
            --exclude=".github" \
            --exclude=".gitignore" \
            --exclude="*.md" \
            --exclude=".node_modules" \
            --exclude="package.json" \
            --exclude="package-lock.json" \
            --exclude="prompts" \
            --exclude="bin" \
            --exclude="sales.md" \
            ./* customs-fees-for-woocommerce/

      # 4. Zip the project
      - name: 📦 Zip the project
        run: zip -r customs-fees-for-woocommerce.zip customs-fees-for-woocommerce/

      # 5. Upload the zipped project as a release asset
      - name: 📤 Upload Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./customs-fees-for-woocommerce.zip
          asset_name: customs-fees-for-woocommerce.zip
          asset_content_type: application/zip

      # 6. All good
      - name: 🎉 All good
        run: echo "All good!"
